######################################################################################
#                               Villages Configuration
######################################################################################
# Discord: https://discord.gg/FmyGDaeFTE
# Config Guide: https://rainchat.gitbook.io/villages/villages-help/villages
######################################################################################
# This file was generated on version 1.5.0
# Plugin made by rain_chat
# Fork of the original Villages (by StefTheDev)
######################################################################################



Settings-Global:
  # languages en_En,ru_Ru...
  default-language: en_EN
  economy-enable: false

Settings-Claim:
  default-title-description: 'A peaceful settlement!'
  # RolePlay/Protect/
  protect-mode: Protect
  default-claim-limit: 6
  default-claim-per-member: 2
  enabled-worlds:
    - world123
  # Removes all inactive villages (time in days)
  expiration:
    time: 5

Economy:
  create-money-take: 5000
  claim-money-take: 800