######################################################################################
#                               Villages Configuration
######################################################################################
# Discord: https://discord.gg/FmyGDaeFTE
# Config Guide: https://rainchat.gitbook.io/villages/villages-help/villages
######################################################################################
# This file was generated on version 1.4.0
# Plugin made by rain_chat
# Fork of the original Villages (by StefTheDev)
######################################################################################



Settings-Global:
  # languages en_En,ru_Ru...
  default-language: en_En


Settings-Claim:

  # RolePlay/Protect/
  protect_mode: Protect
  default-claim-limit: 6
  enabled-worlds:
    - world

  # Removes all inactive villages (time in days)
  expiration:
    time: 5
