######################################################################################
#                               Villages Configuration
######################################################################################
# Discord: https://discord.gg/FmyGDaeFTE
# Config Guide: https://rainchat.gitbook.io/villages/villages-help/villages
######################################################################################
# Plugin made by rain_chat
# Fork of the original Villages (by StefTheDev)
######################################################################################



Settings-Global:
  # languages en_En,ru_Ru...
  default-language: en_EN
  economy-enable: false

Settings-Claim:
  default-title-description: 'A peaceful settlement!'
  # RolePlay/Protect/
  protect-mode: Protect
  nearby-chunks: false
  default-claim-limit: 8
  default-claim-per-member: 3
  enabled-worlds:
    - world
  # Removes all inactive villages (time in days)
  expiration:
    time: 5

Placeholders:
    enable-flag: '&aenable'
    disable-flag:  '&cdisable'
    exapmle-color: '<#12345>'

Economy:
  create-money-take: 5000
  claim-money-take: 800